--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Laith98Dev/HeadshotSound
build-by-default: true
branches:
- main
projects:
  HeadshotSound:
    path: ""
    icon: "20220411_032216.png"
...
